config/routes.rb
Eve::Application.routes.draw do
  
  get '/characters/import' => 'characters#import', as: :import_characters
  devise_for :users,
             :controllers => {
               :registrations => 'custom_devise/registrations',
               :sessions => 'custom_devise/sessions'
             }
  resources :characters, :only => [:index, :show]
  resources :users do
    resources :characters, :except => [:new, :edit, :create, :update] do
      post :bulk_create, :on => :collection
    end
  end

  
  get 'dashboard/index'
  
  root :to => 'dashboard#root'
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  
  attr_protected :user_id, :name, :character_id
  
  validates_presence_of :name, :character_id, :user
  validates_uniqueness_of :character_id
  # we don't *really* need to validate api stuff since
  # characters are only created through the import view
  
  def to_s
    name
  end
  
  def portrait_url(size=nil)
    size = 64 if size.nil? or size.blank? or size < 64
    size = 512 if size > 512
    "http://image.eveonline.com/Character/#{character_id}_#{size}.jpg"
  end
  
  def api
    user.api
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /users/1/characters/import
  def import
    @characters = current_user.api.account.characters.characters
  end
  
  # POST /users/1/characters
  # POST /users/1/characters.json
  def bulk_create
    current_user.characters.destroy_all
    current_user.default_character_id = nil
    current_user.save
    
    characters = []
    ok = true
    params[:import].each do |character_id|
      c = Character.new(:user => current_user)
      c.name = params[:name][character_id]
      c.character_id = character_id
      ok = false unless c.save
      characters << c
    end
    
    unless characters.empty?
      default = Character.where(:character_id => params[:default]).first
      default = characters.first unless default # user didn't select a default
      current_user.default_character_id = default.id
      current_user.save
    end
    
    if ok
      respond_to do |format|
        if characters.empty?
          notice = "No characters imported."
        else
          notice = 'Characters successfully imported.'
        end
        format.html { redirect_to user_characters_path, notice: notice }
      end
    else
      redirect_to user_characters_path(current_user), :alert => "There was an error importing some or all of the characters."
    end
  end
  
  # GET /characters
  # GET /characters.json
  def index
    if params[:user_id]
      @characters = User.find(params[:user_id]).characters
    else
      @characters = Character.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # DELETE /users/1/characters/1
  # DELETE /users/1/characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :ok }
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_as_list_item.erb
<%= image_tag character.portrait_url %>
<span class='text'>
<span class='line'><%= link_to character, character %></span>
<span class='line'><%= link_to character.user, character.user %></span>
<span class='line'><%= character.user.status %></span>
</span>

app/views/characters/import.html.erb
<h1>Listing importable characters</h1>
<%= form_tag bulk_create_user_characters_path(current_user) do %>
  <table>
    <tr>
      <th>Name</th>
      <th>Import?</th>
      <th>Default?</th>
    </tr>

  <% @characters.each do |character| %>
    <tr>
      <td><%= character.name %><%= hidden_field_tag "name[#{character.character_id}]", character.name %></td>
      <td><%= check_box_tag "import[]", character.character_id, (current_user.characters.map{|c| c.character_id}.include? character.character_id ? :checked : "") %></td>
      <td><%= radio_button_tag "default", character.character_id, (current_user.default_character and current_user.default_character.character_id == character.character_id ? :selected : "") %></td>
    </tr>
  <% end %>
  </table>
  <%= submit_tag "Submit" %>
<% end %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>ID</th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.character_id %></td>
    <td><%= link_to 'Show', character %></td>
  </tr>
<% end %>
</table>

<% if current_user.id.to_s == params[:user_id] %>
<br />
<%= link_to 'Import Characters', import_characters_path %>
<% end %>

app/views/characters/show.html.erb
<p>
  <b>Character owned by:</b><br>
  <%= link_to @character.user, @character.user %>
<p>
  <b>Portrait:</b><br>
  <%= image_tag @character.portrait_url 128 %>
</p>
<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<%= link_to "#{@character.user}'s characters", user_characters_path(@character.user) %> |
<%= link_to "All characters", characters_path %>