config/routes.rb
Eve::Application.routes.draw do
  
  get '/characters/import' => 'characters#import', as: :import_characters
  devise_for :users,
             :controllers => {
               :registrations => 'custom_devise/registrations',
               :sessions => 'custom_devise/sessions'
             }
  resources :characters, :only => [:index, :show]
  resources :users do
    resources :characters, :except => [:new, :edit, :create, :update] do
      post :bulk_create, :on => :collection
    end
  end

  
  get 'dashboard/index'
  
  root :to => 'dashboard#root'
end

app/views/layouts/_nav.html.erb
<div id='nav'>
  <% if current_user %>
    Welcome, <%= current_user.first_name or current_user.email %>!
  <% end %>
  <ul>
    <li><%= link_to "Dashboard", dashboard_index_path %>
  </ul>
  <em><strong>Account</strong></em>
  <ul>
    <% if current_user %>
      <li><%= link_to "Manage Characters", user_characters_path(current_user) %></li>
      <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
      <li><%= link_to "Edit Account", edit_registration_path(current_user) %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to "Create Account", new_user_registration_path %></li>
      <li><%= link_to "Log In", new_user_session_path %></li>
    <% end %>
  </ul>
  <em><strong>Server</strong></em>
  <ul>
    <li><%= @api.server_status.server_open ? "Available" : "Unavailable" %></li>
    <!-- <li>Time: <%= @api.server_status.current_time.strftime("%k%M") %> -->
    <li><%= @api.server_status.online_players %> Online</li>
  </ul>
</div>

app/views/layouts/_who.html.erb
<div id='who'><ul>
  <% User.order(:current_sign_in_at).each do |user|
    # TODO we need some way for users to select the character they're playing as for a session
    # for now just use the default
    if user.current_character
    %>
    <li><%= render "characters/as_list_item", :character => user.current_character %></li>
  <% end end %>
</ul></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eve</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/nav" %>
  <div id='main'>
    <p id='notice'><%= notice %></p>
    <%= yield %>
  </div>
  <%= render "layouts/who" %>

</body>
</html>